### ISSUE TITLE
Asahi Alternative Distros list

### ISSUE THREAD

**Issue by tobhe** [pop-os/pop-arm64#12]
Hi!

This project is listed in the Asahi Linux wiki as an alternative distro port for Apple Silicon here: https://github.com/AsahiLinux/docs/wiki/SW%3AAlternative-Distros
I was wondering if that still makes sense since the project focus seems to have shifted to generating a general purpose arm64 image.
I couldn't find any documentation on how to use it on Apple Silicon. Is this still supported? Would it make sense to remove it from the list if that is not the case?

**Comment by leviport** [comment]
We don't maintain the Asahi wiki. Our arm64 image was only ever targeted towards raspi, so Apple silicon is out of scope for its current incarnation. There is a guide linked to from that very wiki page, but it's likely grown stale at this point, as I doubt Lucy is interested in maintaining it any longer.

**Comment by tobhe** [comment]
Thanks @leviport! The linked guide redirects to this repo, that's why I'm asking here. I am asking because I would't want to remove it without your confirmation that it is no longer maintained.

**Comment by leviport** [comment]
Ah sorry, I thought it linked to a guide Lucy wrote. Yeah, removing it is fine. We never intended it to be used on Apple silicon in the first place. Lucy did get it working a while ago, but I doubt she's interested in maintaining any guides or anything. She certainly has no obligation to at this point.
