### ISSUE TITLE
Can’t found bootstrap.sh

### ISSUE THREAD

**Issue by jknbvl** [pop-os/pop-arm64#4]
Sorry, but in newer versions I can’t found bootstrap.sh. How can I compile the OS? Thank you

**Comment by Absolucy** [comment]
The scripts are currently being rewritten to be more general, apologies. You could check out [commit 8cf50c](https://github.com/pop-os/pop-arm64/tree/8cf50c91016db55074b3cee6a016ec29e103707d) in the meantime.
