### ISSUE TITLE
Conflicts in dependencies

### ISSUE THREAD

**Issue by thefossguy** [pop-os/pop-arm64#5]
The README says that the dependencies are `binfmt-support qemu qemu-user-static qemu-user-binfmt`, but `qemu-user-binfmt` and `qemu-user-static` conflict with each other. :(

**Comment by Absolucy** [comment]
ah, get rid of `qemu-user-static` then?

**Comment by thefossguy** [comment]
> ah, get rid of `qemu-user-static` then?

Quite the opposite. Please review PR #6
